**Aplicaciones en ciencia de datos**

**Laboratorio 4**

María Paula Angulo Collantes - 202212044

Danna Gabriela Castro Villalba - 202615188

In [1]:
import pandas as pd

In [5]:
df=pd.read_csv("ecommerce_sales_customer_behavior.csv")
df

,order_id,year,month,quarter,is_weekend_order,platform,country,customer_segment,customer_age_group,customer_gender,...,return_reason,customer_satisfaction,session_duration_minutes,pages_viewed,cart_abandoned_before,wishlist_used,coupon_used,subscription_member,repeat_purchase_count,loyalty_points
0,ORD0000001,2022,4,Q2,Yes,AliExpress,Germany,New Customer,35-44,Male,...,NaN,Dissatisfied,78.7,2,Yes,No,No,No,0,0
1,ORD0000002,2023,6,Q2,Yes,Flipkart,Australia,Loyal Customer,35-44,Male,...,NaN,Neutral,18.2,7,No,Yes,No,No,9,198
2,ORD0000003,2022,2,Q1,Yes,Amazon,Turkey,VIP Customer,45-54,Male,...,NaN,Very Dissatisfied,5.1,1,No,No,No,Yes,30,1020
3,ORD0000004,2022,7,Q3,No,AliExpress,USA,New Customer,35-44,Male,...,NaN,Satisfied,22.0,6,Yes,No,No,Yes,0,0
4,ORD0000005,2024,4,Q2,No,Daraz,Australia,Loyal Customer,35-44,Female,...,NaN,Satisfied,4.5,8,Yes,No,Yes,No,13,598
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,ORD0009996,2022,3,Q1,No,Amazon,Australia,VIP Customer,45-54,Male,...,NaN,Very Satisfied,14.1,6,No,No,No,Yes,47,2021
9996,ORD0009997,2021,11,Q4,No,Amazon,India,VIP Customer,45-54,Female,...,NaN,Satisfied,44.5,8,No,No,No,No,37,814
9997,ORD0009998,2021,10,Q4,Yes,eBay,Pakistan,Loyal Customer,65+,Male,...,NaN,Satisfied,8.9,8,Yes,No,No,No,5,50
9998,ORD0009999,2023,2,Q1,Yes,eBay,Bangladesh,New Customer,35-44,Female,...,NaN,Satisfied,62.4,4,No,Yes,Yes,No,0,0
9999,ORD0010000,2023,6,Q2,No,Shopify Store,India,VIP Customer,18-24,Male,...,NaN,Satisfied,14.0,2,No,No,No,No,32,928

**Punto 1**

In [5]:
df.columns

Index(['order_id', 'year', 'month', 'quarter', 'is_weekend_order', 'platform',
       'country', 'customer_segment', 'customer_age_group', 'customer_gender',
       'acquisition_channel', 'device_used', 'product_category',
       'unit_price_usd', 'quantity_ordered', 'order_value_usd', 'discount_pct',
       'discount_amount_usd', 'final_amount_usd', 'shipping_cost_usd',
       'tax_amount_usd', 'total_paid_usd', 'payment_method', 'shipping_method',
       'delivery_days', 'product_rating', 'review_submitted', 'returned',
       'return_reason', 'customer_satisfaction', 'session_duration_minutes',
       'pages_viewed', 'cart_abandoned_before', 'wishlist_used', 'coupon_used',
       'subscription_member', 'repeat_purchase_count', 'loyalty_points'],
      dtype='object')

In [6]:
(df["total_paid_usd"]>500).sum()

3562

**Punto 2**

In [8]:
Porcentaje=(df["customer_segment"]=="VIP Customer").mean() * 100
print(Porcentaje,"%")

12.13 %

**Punto 3**

In [9]:
df[(df["customer_gender"] == "Female") & (df["customer_age_group"] == "25-34")].shape[0]

1471

**Punto 4**

In [10]:
df[
    (df["returned"] == "Yes") &
    (df["customer_satisfaction"].isin(["Dissatisfied", "Very Dissatisfied"]))
].shape[0]

69

In [13]:
df[
    (df["returned"] == "Yes") &
    (df["customer_satisfaction"].isin(["Dissatisfied", "Very Dissatisfied"]))
]["product_category"].value_counts().head(1)

product_category
Electronics    12
Name: count, dtype: int64

**Punto 5**

In [14]:
pedidos_fin_semana = df[df["is_weekend_order"] == "Yes"]

pedidos_cupon = pedidos_fin_semana[
    pedidos_fin_semana["coupon_used"] == "Yes"
]

porcentaje_cupon = (
    len(pedidos_cupon) / len(pedidos_fin_semana)
) * 100

print("Pedidos realizados en fin de semana:", len(pedidos_fin_semana))
print("Pedidos de fin de semana que utilizaron cupón:", len(pedidos_cupon))
print("Porcentaje que utilizó cupón:", round(porcentaje_cupon, 2), "%")

Pedidos realizados en fin de semana: 3813
Pedidos de fin de semana que utilizaron cupón: 1367
Porcentaje que utilizó cupón: 35.85 %

**Punto 6**

In [16]:
inactive = df[
    (df["customer_segment"] == "Inactive Customer") &
    (df["discount_pct"] > 30)
]

print("Cantidad de pedidos:", len(inactive))
print("Monto promedio pagado:", round(inactive["total_paid_usd"].mean(), 2))

Cantidad de pedidos: 72
Monto promedio pagado: 403.4

**Punto 7**

In [17]:
resumen_ventas = df[
    [
        "country",
        "platform",
        "product_category",
        "year",
        "month",
        "total_paid_usd"
    ]
]

resumen_ventas

,country,platform,product_category,year,month,total_paid_usd
0,Germany,AliExpress,Home & Kitchen,2022,4,456.39
1,Australia,Flipkart,Beauty & Personal Care,2023,6,149.02
2,Turkey,Amazon,Electronics,2022,2,5783.94
3,USA,AliExpress,Health & Wellness,2022,7,221.94
4,Australia,Daraz,Automotive,2024,4,344.71
...,...,...,...,...,...,...
9995,Australia,Amazon,Mobile & Tablets,2022,3,965.01
9996,India,Amazon,Food & Grocery,2021,11,292.83
9997,Pakistan,eBay,Books & Education,2021,10,61.78
9998,Bangladesh,eBay,Food & Grocery,2023,2,89.92
9999,India,Shopify Store,Beauty & Personal Care,2023,6,277.14

**Punto 8**

In [18]:
df["ahorro_pct_real"] = (
    df["discount_amount_usd"] / df["order_value_usd"]
) * 100

df[["order_value_usd", "discount_amount_usd", "discount_pct", "ahorro_pct_real"]]

      order_value_usd  discount_amount_usd  discount_pct  ahorro_pct_real
0              539.34               107.87            20        20.000371
1              150.00                37.50            25        25.000000
2             6000.00               900.00            15        15.000000
3              214.85                10.74             5         4.998836
4              400.47               120.14            30        29.999750
...               ...                  ...           ...              ...
9995           972.17                97.22            10        10.000309
9996           360.55               108.16            30        29.998613
9997            65.50                16.38            25        25.007634
9998            82.04                 8.20            10         9.995124
9999           300.00                45.00            15        15.000000

[10000 rows x 4 columns]

No necesariamente coinciden siempre. La razón es que discount_pct puede haber sido calculado o registrado con un porcentaje redondeado, mientras que ahorro_pct_real se calcula directamente a partir de:

$$ \mathtt{ahorro\_pct\_real} = \frac{\mathtt{discount\_amount\_usd}}{\mathtt{order\_value\_usd}} $$

Por eso pueden existir pequeñas diferencias por redondeo.

**Punto 9**

In [19]:
df["compra_grande"] = df["quantity_ordered"] > 2

compras_grandes = df[df["compra_grande"] == True]

porcentaje_devoluciones = (
    (compras_grandes["returned"] == "Yes").sum()
    / len(compras_grandes)
) * 100

print("Compras grandes:", len(compras_grandes))
print("Compras grandes devueltas:", (compras_grandes["returned"] == "Yes").sum())
print("Porcentaje de compras grandes devueltas:", round(porcentaje_devoluciones, 2), "%")

Compras grandes: 1947
Compras grandes devueltas: 125
Porcentaje de compras grandes devueltas: 6.42 %

**Punto 10**

In [20]:
df_ordenado = df.sort_values("total_paid_usd", ascending=False)

top_10 = df_ordenado.head(10)

top_10[
    [
        "order_id",
        "total_paid_usd",
        "country",
        "product_category",
        "platform"
    ]
]

        order_id  total_paid_usd   country product_category    platform
6933  ORD0006934        11829.02   Nigeria      Electronics      Amazon
9120  ORD0009121        10672.50        UK      Electronics    Flipkart
1904  ORD0001905        10566.55    Turkey      Electronics       Daraz
3537  ORD0003538         9558.47  Pakistan      Electronics       Jumia
5843  ORD0005844         8996.51       UAE      Electronics      Amazon
4292  ORD0004293         8975.51  Pakistan      Electronics       Jumia
960   ORD0000961         8817.56     Egypt      Electronics    Flipkart
153   ORD0000154         8570.46       UAE      Electronics  AliExpress
8044  ORD0008045         8542.20    Canada      Electronics        Etsy
13    ORD0000014         8141.50       UAE      Electronics  AliExpress

In [21]:
print("Países:")
print(top_10["country"].value_counts())

print("\nCategorías:")
print(top_10["product_category"].value_counts())

print("\nPlataformas:")
print(top_10["platform"].value_counts())

Países:
country
UAE         3
Pakistan    2
Nigeria     1
UK          1
Turkey      1
Egypt       1
Canada      1
Name: count, dtype: int64

Categorías:
product_category
Electronics    10
Name: count, dtype: int64

Plataformas:
platform
Amazon        2
Flipkart      2
Jumia         2
AliExpress    2
Daraz         1
Etsy          1
Name: count, dtype: int64

**PUnto 11**